language: python
python:
  - "3.6"      # current default Python on Travis CI
script:
  - python3 -m unittest tests.test_docs
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=0.2.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q ssh://git@github.com/jepperaskdk/pydoctest --tags
  - sed -i "s/REPLACED_BY_TRAVIS/${GIT_TAG}/g" setup.py
deploy:
  provider: pypi
  username: "pypi-AgEIcHlwaS5vcmcCJDUzZGMwNzRjLWUzNTktNDIxNS04OWVkLTU3ZjllZTI1Y2QxZAACOnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJweWRvY3Rlc3QiXX0sICJ2ZXJzaW9uIjogMX0AAAYgK2xaqlyQbNc4sR1AzfJbxxvlWHo8OGFjXtAsT0IQo-0"
  password:
    secure: "xyyO4aYNV19Ri1y/Uc6t1Apu6ALi3syQmzsAEd5BUw0+IuU5OYmXi+cwaNv7Do6vPeGhT98IJttXpfX6iPMAU7l6y6Votd2Il7GaDx6p0BSmEKH0jrMLGfivZMe2whjr9Xpoh/5lYQbZyDBAp3Arw665T1oefnsbxkG8FklENgcTDlCgPxkjXdWHiqtUnJI+79MSzB3cjglvuOT8Ooyt+Czvrsr/IYuTZq1SL9m6q8+50J9vr+iYW6eoChOCoC8nJYX1zUI4maCHNTgyleG0FBGZpiieMyyfCKb4vXh7f0xJ3bgeh1Ij2WQgPoJf0PLtYL+O69ahfcsBQfZJyp/l9XAA8qGSHpC+bplsbfEKdopb0iFnVNa5GHMl6oRRxWrJTSXNT6F1V9TKC6nm4dtVWt3Q6775mmGyQJVx91geKCQ60WVd6LovOG56dRvwzaIt6ZApgeXsmunXe2kE7Z+D7PkeJC+DHT5KwNnb9VZ5z6bcIfXFPxwQYdCXQDVt6eR1G24vqGRDY9M86BepuH7XGfQIHUzW7/CqI0RnB0e90pPoEIFeXo8ZRKWhTHuReo3I0xLXMsAYHexUdfLKWcnqq1XBxFItW+rspxX+jwwbHLXEcho7XtHmDsSmNrHOv7VMLUCcsS3cjNLO0BSZNQSN5VHSBuN256cvATi4l/qqx8o="